import 'package:bima_g/main.dart' as app;
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';


void main() async {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  testWidgets("Bimag APP: Integration Testing", (WidgetTester tester) async {
    app.main();
    await tester.pumpAndSettle();

    //Language Module
    await tester.tap(find.byKey(Key('language_0_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('continue_key')));
    await tester.pump(Duration(seconds: 2));


    //Info Sliders Module
    for (int i = 0; i <= 3; i++) {
      await tester.tap(find.byKey(Key('info_sliders_key')));
      await tester.pump();
    }
    await tester.pump(Duration(seconds: 1));
    await tester.tap(find.byKey(Key('check_box_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('verify_num_n_login_key')));
    await tester.pump(Duration(seconds: 2));


    //Login Module
    await tester.tap(find.byKey(Key('mobile_no_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('mobile_no_key')), '6305889568');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('login_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('password_field_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('password_field_key')), '1234567890');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('login_key')));
    await tester.pump(Duration(seconds: 2));


    //Home Module
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('home_tab_key')));
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('insurance_0_type')), // what you want to find
      find.byKey(ValueKey('list_view_key')), // widget you want to scroll
      const Offset(-250, 0),// delta to move
    );


    //Bike Insurance Module
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('insurance_0_type')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Bought a new bike?'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Kolkata'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('WB04'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('Yamaha'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('Yamaha FZ S FI'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('FZ S FI Deluxe BS6'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('2014'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('verify_details_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey( Key('view_quotes_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Bought a new bike?'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Search City'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select City Here'));
    await tester.pumpAndSettle();
    await tester.enterText((find.byKey(Key('search_key'))), 'Chen');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Chennai'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Search RTO'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select RTO Here'));
    await tester.pumpAndSettle();
    await tester.enterText((find.byKey(Key('search_key'))), 'TN');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('TN05'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Search Manufacturer'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select Manufacturer Here'));
    await tester.pumpAndSettle();
    await tester.enterText((find.byKey(Key('search_key'))), 'Roy');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Royal Enfield'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Search Model'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select Model Here'));
    await tester.pumpAndSettle();
    await tester.enterText((find.byKey(Key('search_key'))), 'Royal');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Royal Enfield Hunter 350'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select Variant'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select Variant Here'));
    await tester.pumpAndSettle();
    await tester.enterText((find.byKey(Key('search_key'))), 'Hunter');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Hunter 350 Metro Dapper'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2006'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('verify_details_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey( Key('view_quotes_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();


    //Car Insurance Module
    await tester.tap(find.byKey(Key('insurance_1_type')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Bought a new car?'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Hyderabad'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('TS13'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('AUDI'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('Q7'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('3.0 TDI'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('2013'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('verify_detailss_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey( Key('view_quotess_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Bought a new car?'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Search City'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select City Here'));
    await tester.pumpAndSettle();
    await tester.enterText((find.byKey(Key('search_keyy'))), 'Gur');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Gurgaon'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Search RTO'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select RTO Here'));
    await tester.pumpAndSettle();
    await tester.enterText((find.byKey(Key('search_keyy'))), 'HR');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('HR55'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Search Manufacturer'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select Manufacturer Here'));
    await tester.pumpAndSettle();
    await tester.enterText((find.byKey(Key('search_keyy'))), 'BM');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('BMW'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Search Model'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select Model Here'));
    await tester.pumpAndSettle();
    await tester.enterText((find.byKey(Key('search_keyy'))), 'SERI');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('7 SERIES'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select Variant'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Select Variant Here'));
    await tester.pumpAndSettle();
    await tester.enterText((find.byKey(Key('search_keyy'))), '73');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('730Ld'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2021'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('verify_detailss_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey( Key('view_quotess_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();

    //Health Insurance Module
    await tester.tap(find.byKey(Key('insurance_2_type')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('View Quotes'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('₹1189'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Name As Per ID Card"), findsOneWidget);
    expect(find.text("Please Enter Pancard No"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('full_namee_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('full_namee_key')), 'Asapu Sri Kumar Manikanta');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pancard_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pancard_key')), 'KCMEJ7865K');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('email_address_key')), // what you want to find
      find.byKey(ValueKey('pancard_key')), // widget you want to scroll
      const Offset(-250, 0),// delta to move
    );
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('email_address_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('email_address_key')), 'kumar@gmail.com');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Emergency No"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('emergency_mob_no_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('emergency_mob_no_key')), '7654390786');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('D_o_B_key')), // what you want to find
      find.byKey(ValueKey('weight_key')), // widget you want to scroll
      const Offset(250, 0),// delta to move
    );
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Date"), findsOneWidget);
    expect(find.text("Please Enter Occupation"), findsAtLeastNWidgets(0));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('D_o_B_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('June 2023'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2019'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('19'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('occupation_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('occupation_key')), 'UX Designer');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('weight_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('weight_key')), '55');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('occupationn_key')), // what you want to find
      find.byKey(ValueKey('spouse_full_name')), // widget you want to scroll
      const Offset(-300, 0),// delta to move
    );
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Spouse's Full Name"), findsOneWidget);
    expect(find.text("Please Enter Date Of Birth"), findsOneWidget);
    expect(find.text("Please Enter Occupation"), findsAtLeastNWidgets(1));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('spouse_full_name')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('spouse_full_name')), 'Sri');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('born_date_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('June 2023'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2019'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('19'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('occupationn_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('occupationn_key')), 'UI');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('weightt_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('weightt_key')), '22');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Save & Continue'));
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('contact_no_key')), // what you want to find
      find.byKey(ValueKey('date_of_birth_key')), // widget you want to scroll
      const Offset(-300, 0),// delta to move
    );
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Nominee Full Name"), findsOneWidget);
    expect(find.text("Please Enter Date Of Birth"), findsOneWidget);
    expect(find.text("Please Enter Contact No"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('relation_type_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('nominee_full_name_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('nominee_full_name_key')), 'Asapu Sukumar');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('date_of_birth_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('June 2023'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2019'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('19'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('contact_no_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('contact_no_key')), '9876543210');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Save & Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Filter'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Below ₹3 lakh'));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Sort By'));
    await tester.pumpAndSettle(Duration(seconds: 2));
    await tester.tap(find.text('Premium low to high'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Cancel'));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Renew your policy'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Self'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Father'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Age"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey( Key('age_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey( Key('age_key')), '55');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Pincode Number"), findsOneWidget);
    expect(find.text("Please Enter Street Address"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pincode_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pincode_key')), '533201');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle(Duration(seconds: 2));
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Select Village"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('village_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('street_address_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('street_address_key')), 'Ashok Nagar');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Existing illness'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Surgical procedure'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Appendix'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('View Plans'));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();


    //Home Insurance Module
    await tester.tap(find.byKey(Key('insurance_3_type')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('View Quotes'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('₹3400'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Name As Per ID Card"), findsOneWidget);
    expect(find.text("Please Enter Date Of Birth"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('full_name_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('full_name_key')), 'Asapu Sri Kumar Manikanta');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('dob_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('June 2023'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2019'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('19'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('email_address_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('email_address_key')), 'kumar@gmail.com');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle(Duration(seconds: 2));
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Pincode Number"), findsOneWidget);
    expect(find.text("Please Enter Street Address"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pincode_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pincode_key')), '533201');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle(Duration(seconds: 2));
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Select Village"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('village_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('street_address_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('street_address_key')), 'Ashok Nagar');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('relationship_key')), // what you want to find
      find.byKey(ValueKey('nominee_name_key')), // widget you want to scroll
      const Offset(-250, 0),// delta to move
    );
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text('Please Enter Nominnee Name'), findsOneWidget);
    expect(find.text('Please Enter Nominnee Age'), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('nominee_name_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('nominee_name_key')), 'Kumari');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('nominee_age_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('nominee_age_key')), '55');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('relationship_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Filter'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('1 Year'));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Sort By'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Premium low to high'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Cancel'));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Renew your policy'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Pincode Number"), findsOneWidget);
    expect(find.text("Please Enter Street Address"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pincode_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pincode_key')), '533201');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle(Duration(seconds: 2));
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Select Village"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('village_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('street_address_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('street_address_key')), 'Ashok Nagar');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('carpet_area_key')), // what you want to find
      find.byKey(ValueKey('value_of_household_items_key')), // widget you want to scroll
      const Offset(-400, 0),// delta to move
    );
    await tester.pumpAndSettle();
    await tester.tap(find.text('View Plans'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Value of Building"), findsOneWidget);
    expect(find.text("Please Enter Value of Household Items"), findsOneWidget);
    expect(find.text("Please Enter Carpet Area"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('value_of_building_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('value_of_building_key')),'500000');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('value_of_household_items_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('value_of_household_items_key')),'100000');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('carpet_area_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('carpet_area_key')),'500');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('View Plans'));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();


    //Register Business Module
    await tester.tap(find.byKey(Key('menu_drawer_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('register_business_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Medical'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle(Duration(seconds: 2));
    await tester.tap(find.byKey(Key('gst_no_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('gst_no_key')),'GSTNO565677780');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('garage_name_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('garage_name_key')),'Kumar Garage');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('company_pan_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('company_pan_key')),'KCMEH5890F');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('business_type_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('business_type_key')),'Normal');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('business_mo_no_key')), // what you want to find
      find.byKey(ValueKey('established_year_key')), // widget you want to scroll
      const Offset(-300, 0),// delta to move
    );
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('business_mo_no_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('business_mo_no_key')),'8568087775');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('whatsapp_no_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('whatsapp_no_key')),'9545457788');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('business_email_add_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('business_email_add_key')),'kumargarage@gmail.com');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Pincode Number"), findsOneWidget);
    expect(find.text("Please Enter Street Address"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pincode_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pincode_key')), '533201');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle(Duration(seconds: 2));
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Select Village"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('village_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('street_address_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('street_address_key')), 'Ashok Nagar');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    expect(find.text("Please Enter Name"), findsOneWidget);
    expect(find.text("Please Enter Date Of Birth"), findsOneWidget);
    expect(find.text("Please Enter Mobile No"), findsOneWidget);
    expect(find.text("Please Enter Pincode Number"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('name_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('name_key')),'Sri');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('d_o_b_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('June 2023'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2019'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('19'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('mobile_number_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('mobile_number_key')),'8345657890');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('alt_mo_no_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('alt_mo_no_key')),'9368876678');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pincode_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pincode_key')), '533201');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle(Duration(seconds: 2));
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('street_address_key')), // what you want to find
      find.byKey(ValueKey('village_dropdown_key')), // widget you want to scroll
      const Offset(-300, 0),// delta to move
    );
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Select Village"), findsOneWidget);
    expect(find.text("Please Enter Street Address"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('village_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('street_address_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('street_address_key')), 'Ashok Nagar');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('account_number_key')), // what you want to find
      find.byKey(ValueKey('ifsc_code_key')), // widget you want to scroll
      const Offset(300, 0),// delta to move
    );
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Account No"), findsOneWidget);
    expect(find.text("Please Enter IFCS Code"), findsOneWidget);
    expect(find.text("Please Enter Bank Name"), findsOneWidget);
    expect(find.text("Please Enter Branch Name"), findsOneWidget);
    expect(find.text("Please Enter Name"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('account_number_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('account_number_key')), '477877879879');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('ifsc_code_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('ifsc_code_key')), 'UCB07789');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('bank_name_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('bank_name_key')), 'Axis Bank');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('branch_name_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('branch_name_key')), 'KPHB Colony');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('name_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('name_key')), 'Sri');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Pincode Number"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pincode_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pincode_key')), '533201');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle(Duration(seconds: 2));
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('street_address_key')), // what you want to find
      find.byKey(ValueKey('village_dropdown_key')), // widget you want to scroll
      const Offset(-300, 0),// delta to move
    );
    await tester.pumpAndSettle();
    await tester.tap(find.text('Continue'));
    await tester.pumpAndSettle();
    expect(find.text("Please Select Village"), findsOneWidget);
    expect(find.text("Please Enter Street Address"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('village_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('street_address_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('street_address_key')), 'Ashok Nagar');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    // // await tester.tap(find.text('Continue'));
    // // await tester.pumpAndSettle(Duration(seconds: 2));
    // // await tester.dragUntilVisible(
    // //   find.byKey(const ValueKey('doc_key')), // what you want to find
    // //   find.byKey(ValueKey('doc_no_key')), // widget you want to scroll
    // //   const Offset(300, 0),// delta to move
    // // );
    // // await tester.pumpAndSettle();
    // // await tester.tap(find.byKey(Key('doc_key')).first);
    // // await tester.pumpAndSettle();
    // // await tester.tap(find.byKey(Key('doc_no_key')));
    // // await tester.pumpAndSettle();
    // // await tester.enterText(find.byKey(Key('doc_no_key')), '932397509374');
    // // await tester.testTextInput.receiveAction(TextInputAction.done);
    // // await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('arrow_right_key')).first);
    await tester.pumpAndSettle();


    //My Profile Module
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('my_profile_key')));
    await tester.pumpAndSettle();


    //Profile Info Page
    await tester.tap(find.byIcon(Icons.keyboard_arrow_right));
    await tester.pumpAndSettle(Duration(seconds: 5));
    await tester.tap(find.byKey(Key('first_name_key')));
    await tester.sendKeyEvent(LogicalKeyboardKey.backspace);
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('first_name_key')), 'Sri Kumar');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('last_name_key')));
    await tester.sendKeyEvent(LogicalKeyboardKey.backspace);
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('last_name_key')), 'Asapu');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('mail_address_key')));
    await tester.sendKeyEvent(LogicalKeyboardKey.backspace);
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('mail_address_key')), 'Kumar@gmail.com');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('select_gender_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('D_O_B_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('June 2016'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2020'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('16'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('street_address_key')), // what you want to find
      find.byKey(ValueKey('D_O_B_key')), // widget you want to scroll
      const Offset(-350, 0),// delta to move
    );
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pincode_key')));
    await tester.sendKeyEvent(LogicalKeyboardKey.backspace);
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pincode_key')), '533201');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pump(Duration(seconds: 2));
    await tester.tap(find.byKey(Key('village_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('street_address_key')));
    await tester.sendKeyEvent(LogicalKeyboardKey.backspace);
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('street_address_key')), '6-4-67/1,Ashok Nagar,533201.');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Save'));
    await tester.pumpAndSettle(Duration(seconds: 1));
    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();


    //Polices Module
    await tester.tap(find.byKey(Key('policies_tab_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.keyboard_arrow_right_outlined).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();

    //Family Module
    await tester.tap(find.byKey(Key('family_tab_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_a_family_member_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_new_family_member_save_key')));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Member's Full Name"), findsOneWidget);
    expect(find.text('Please Enter Date Of Birth'), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('relationship_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('member_full_name_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('member_full_name_key')), 'Sri');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('DOB_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('June 2023'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2016'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('20'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('gender_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_new_family_member_save_key')));
    await tester.pump(Duration(seconds: 2));
    await tester.tap(find.byKey(Key('family_member_edit_key')).at(0));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('relationship_dropdown_key')).last);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('member_full_name_key')));
    await tester.sendKeyEvent(LogicalKeyboardKey.backspace);
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('member_full_name_key')), 'Kumari');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('DOB_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('June 2016'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2019'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('20'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('gender_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_new_family_member_save_key')));
    await tester.pumpAndSettle();


    //Assets Module
    await tester.tap(find.byKey(Key('assets_tab_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_new_assets_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_new_assets_save_key')));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Registration Number"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Property'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Owned'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_new_assets_save_key')));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter City Name"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('city_field_key')));
    await tester.enterText(find.byKey(Key('city_field_key')), 'Amalapuram');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('age_of_property_key')));
    await tester.enterText(find.byKey(Key('age_of_property_key')), '5');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('structure_value_key')));
    await tester.enterText(find.byKey(Key('structure_value_key')), '8000000');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('No'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('assets_policy_expire_date_key'),));
    await tester.pumpAndSettle();
    await tester.tap(find.text('June 2023'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('2019'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('19'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_new_assets_save_key')));
    await tester.pumpAndSettle();


    //Address Module
    await tester.tap(find.byKey(Key('address_tab_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_a_new_address_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_new_address_save_key')));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Pincode Number"), findsOneWidget);
    expect(find.text("Please Enter Street Address"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('address_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pincode_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pincode_key')), '533201');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pump(Duration(seconds: 3));
    await tester.tap(find.byKey(Key('add_new_address_save_key')));
    await tester.pumpAndSettle();
    expect(find.text("Please Select Village"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('village_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('street_address_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('street_address_key')), '6-4-67/1,Ashok nagar,Amalapuram,533201');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_new_address_save_key')));
    await tester.pump(Duration(seconds: 2));
    await tester.tap(find.byKey(Key('address_edit_key')).at(0));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('address_dropdown_key')).last);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pincode_key')));
    await tester.sendKeyEvent(LogicalKeyboardKey.backspace);
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pincode_key')), '500062');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pump(Duration(seconds: 3));
    await tester.tap(find.byKey(Key('village_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('street_address_key')));
    await tester.sendKeyEvent(LogicalKeyboardKey.backspace);
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('street_address_key')), 'North Kamala Nagar');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_new_address_save_key')));
    await tester.pumpAndSettle();


    // // //Document Module
    // await tester.tap(find.byKey(Key('document_tab_key')));
    // await tester.pumpAndSettle();
    // await tester.tap(find.byKey(Key('add_a_new_document_key')));
    // await tester.pumpAndSettle();
    // await tester.tap(find.byKey(Key('document_type_key')).first);
    // await tester.pumpAndSettle();
    // await tester.tap(find.byKey(Key('document_no_key')));
    // await tester.pumpAndSettle();
    // await tester.enterText(find.byKey(Key('document_no_key')), '932397509374');
    // await tester.testTextInput.receiveAction(TextInputAction.done);
    // await tester.pumpAndSettle();
    // await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    // await tester.pumpAndSettle(Duration(seconds: 2));


    //Previous tabs and Home tab
    await tester.tap(find.byKey(Key('address_tab_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('assets_tab_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('family_tab_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('policies_tab_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('home_tab_key')));
    await tester.pumpAndSettle();


    //Near By Module
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('nearby_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('drop_down_key')));
    await tester.pumpAndSettle();
    await tester.dragUntilVisible(
      find.byKey(const ValueKey('add_address_key')), // what you want to find
      find.byKey(ValueKey('list_key')), // widget you want to scroll
      const Offset(-800, 0),// delta to move
    );
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('add_address_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Save'));
    await tester.pumpAndSettle();
    expect(find.text("Please Enter Pincode Number"), findsOneWidget);
    expect(find.text("Please Enter Street Address"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('address_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('pincode_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('pincode_key')), '533201');
    await tester.pump(Duration(seconds:3));
    await tester.tap(find.text('Save'));
    await tester.pumpAndSettle();
    expect(find.text("Please Select Village"), findsOneWidget);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('village_dropdown_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('street_address_key')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(Key('street_address_key')), '6-4-67/1,Ashok nagar,Amalapuram,533201');
    await tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.pumpAndSettle();
    await tester.tap(find.text('Save'));
    await tester.pumpAndSettle(Duration(seconds: 2));
    await tester.tap(find.byKey(Key('rounded_check_box_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('drop_down_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('business_call_key')).first);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('info_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('services_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('photos_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('reviews_key')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Write a review'));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios_new));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_back_ios));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('home_tab_key')));
    await tester.pumpAndSettle();
  });
}